version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 5555:80
